quick-start/terraform/ec2_assets/job/hippo.nomad
quick-start/terraform/main.tf

bump to hippo 0.14.1

---

quick-start/terraform/main.tf

No changes to the main project; feel free to ignore

hippo v0.15.1

---

quick-start/README.md
quick-start/terraform/outputs.tf

Some misc docs improvements based on feedback from @adamreese

docs(quick-start): update README.md to use spin new; export DNS_DOMAIN

---

local/start.sh

Signed-off-by: Lann Martin <lann.martin@fermyon.com>

local: Ensure data/ dir can be deleted on Linux

---

local/start.sh

fix(local): wait for consul to be ready before running jobs

---

local/README.md
local/job/bindle.nomad
local/job/traefik.nomad
local/start.sh

Have nomad download Traefik and Bindle when starting their jobs.

feat(local): Use nomad to download job artifacts

---

local/start.sh

Signed-off-by: Lann Martin <lann.martin@fermyon.com>

fix: Wait for nomad after nomad starts

---

local/job/hippo.nomad

Signed-off-by: Brian H <brian.hardock@fermyon.com>

fix(hippo): update to 0.17.0

---

local/job/hippo.nomad

fix(local): use rawexec for hippo jobs

---

aws/terraform/ec2_assets/job/hippo.nomad
aws/terraform/main.tf
aws/terraform/scripts/user-data.sh
local/job/hippo.nomad

EDIT: now working with both the local and AWS installers. Ready for review!
~~Currently working through a style sheet bug, but here's a preview!~~
~~The color scheme from fermyon/styleguide is not being applied to the project. Currently working through that. Hold up~~

Fermyon-branded Hippo

---

aws/README.md

Prevents confusion between this guide and the quick start on fermyon.dev
Signed-off-by: Michelle Noorali <michelle@fermyon.com>

Update header to prevent confusion

---

aws/terraform/variables.tf

* Updates the default value for the instance_name variable to 'fermyon'

ref(aws): update default instance name

---

deploy.md

Ref https://github.com/fermyon/installer/issues/66
@itowlson hoping for your feedback on these additions when convenient.

docs(deploy.md): add note on app availability timing

---

README.md

Signed-off-by: Hanzhen Liang <handrenliang@gmail.com>

docs: fix deploy broken link

---

.github/workflows/build.yml
docs/content/index.md
docs/content/open-source.md
docs/content/quickstart-aws.md
docs/content/quickstart-local.md

* fixes CI
* updates `url` fields on applicable content .md files

fix(*): update urls and ci

---

share/terraform/dependencies.yaml

Signed-off-by: Antonette Caldwell <pullmana8@gmail.com>

feat(local): Bump spin to `v0.4.0` #83

---

README.md
digitalocean/.gitignore
digitalocean/README.md
digitalocean/terraform/main.tf
digitalocean/terraform/outputs.tf
digitalocean/terraform/providers.tf
digitalocean/terraform/variables.tf
share/terraform/vm_assets/run_servers.sh

Add digitalocean

---

docs/config/site.toml
docs/templates/content_top.hbs

Signed-off-by: flynnduism <ronan@fermyon.com>

docs(chore): add ga and cookie consent

---

README.md

Adds link to the Azure installation docs
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>

feat: add azure

---

README.md

* Add links to cloud providers

docs(README.md): add cloud provider links

---

local/job/hippo.nomad

to allow setting initial user and password
Signed-off-by: Steven Murawski <stmuraws@microsoft.com>

update local installer nomad configuration for Hippo 

---

azure/terraform/main.tf

Refs: https://github.com/fermyon/installer/pull/110
Signed-off-by: Konstantin Shabanov <mail@etehtsea.me>

chore(azure): Use shared deps

---

README.md

Signed-off-by: Klaus Hebsgaard <khebbie@users.noreply.github.com>

update to links - they are inside the terraform folder

---

README.md
civo/.gitignore
civo/README.md
civo/terraform/main.tf
civo/terraform/outputs.tf
civo/terraform/providers.tf
civo/terraform/variables.tf

Signed-off-by: Saiyam Pathak <saiyam911@gmail.com>
Civo provider for Fermyon

Civo provider for Fermyon

---

README.md
equinix-metal/.gitignore
equinix-metal/README.md
equinix-metal/terraform/main.tf
equinix-metal/terraform/outputs.tf
equinix-metal/terraform/providers.tf
equinix-metal/terraform/setup-bgp.sh
equinix-metal/terraform/variables.tf

This example uses a Global IP via BGP to allow low-latency routing to multiple platform servers

feat: example of Equinix Metal deployment

---

.github/workflows/deploy.yml

Only deploy website if org is fermyon (disable for forks)

chore(deploy.yml): only attempt website deploy if org is fermyon
