quick-start/README.md, quick-start/terraform/outputs.tf
Applies two improvements kindly suggested by @lgfa29:
* Collapse relevant environment exports into one `environment` output
* Demonstrate the preferred mode of accessing Nomad and Consul via SSH tunnels
=> feat(quick-start): add environment output; update README

quick-start/README.md
I noticed that this is the domain registered in Traefik, and it's the one that worked for me.
=> docs(quick-start): fix URL for hello-world app

quick-start/README.md, quick-start/terraform/ec2_assets/job/bindle.nomad, quick-start/terraform/ec2_assets/job/hippo.nomad, quick-start/terraform/ec2_assets/job/traefik.nomad, quick-start/terraform/ec2_assets/run_servers.sh, quick-start/terraform/main.tf, quick-start/terraform/outputs.tf, quick-start/terraform/scripts/user-data.sh, quick-start/terraform/variables.tf
Update automation such that the default URLs are http-based but with option to use LE for tls.
Closes https://github.com/fermyon/nomad-aws-demo/issues/16
=> ref(quick-start): Use http for services if Let's Encrypt is disabled

local/quick-start/start.sh
This ensures that Nomad inherits the current user's PATH environment variable,
rather that the default sudo behavior of using a sanitized PATH.
This is necessary because the user may have installed bindle-server, traefik,
etc. locally but not system-wide. For example, cargo install installs in the
current user's home directory by default.
Signed-off-by: Joel Dice <joel.dice@gmail.com>
=> fix: add --preserve-env=PATH to sudo command

local/job/hippo.nomad
Signed-off-by: Mikkel Mørk Hegnhøj <mikkel@fermyon.com>
Fixes removing Nomad jobs form Hippo (and probably more).
=> Updating Hippo to v0.16.3 for local installer

local/job/hippo.nomad, local/start.sh
See https://github.com/fermyon/nomad-local-demo/blob/579af01653c5a365047577869dec119c6529a4c3/job/hippo-linux.nomad#L43
closes #36
=> start hippo job with raw_exec driver

README.md, aws/README.md, deploy.md, local/README.md
* Re-orgs installer docs and adds a unified app deploy guide
Closes https://github.com/fermyon/installer/issues/30
=> docs(*): re-org and add unified deploy guide

aws/README.md
* Adds the naming pattern to each provisioned resource, in case users need to manually clean up.
=> docs(aws/README.md): list given name for each provisioned resource

aws/README.md, aws/terraform/main.tf, aws/terraform/outputs.tf
* Adds a set of `common_tags` (in this PR currently we just have one) to be applied to all resources, enabling manual cleanup if needed.
Two considerations:
- I initially started down the [default_tags](https://www.hashicorp.com/blog/default-tags-in-the-terraform-aws-provider) path; however, with this approach, the tag values need to be known prior to apply, i.e. static.  If we're okay with something static like `"FermyonInstaller" = true`, then we could go this route and it would clean up the code a bit (remove the `merge` of common_tags and resource-specific tags)
- @lann initially suggested a tag with a timestamp as a value.  I opted not to go this route as it would both require updates to all applicable resources on any/every `terraform apply` and the tag value itself didn't seem …
=> feat(aws): apply common tags to all resources

local/bindle/Dockerfile.bindle-static, local/job/bindle.nomad
This should resolve any glibc compat issues.
=> Statically link vendored Linux `bindle-server`

azure/README.md
Vault is not currently configured to use a certificate. You need to configure the status command to hit the HTTP endpoint rather than the HTTPS endpoint.
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
Before change
```shell
ubuntu@myfermyonvm:~$ vault status
Error checking seal status: Get "https://127.0.0.1:8200/v1/sys/seal-status": http: server gave HTTP response to HTTPS client
```
After change
```shell
ubuntu@myfermyonvm:~$ vault status -address http://127.0.0.1:8200
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.10.3
Storage Type    file
Cluster Name    vault-cluster-268aeb56
Cluster ID      cf18c03a-b14e-ecf4-895f-33643ba4833a
HA Enabled      false
```
=> Update vault status command

local/start.sh
This is a first-time user experience improvement.
Since nomad, consul, and spin all have native Windows releases,
running the installer from a Windows git bash environment (msys) sort of works,
but the traefik job fails internally, without a clear reason in the console (other than "it took too long").
The source of the failure is buried in the nomad.log, since the traefik component download 404-ed
because the windows release is a zip, not a tar.gz.
The added OS environment check at the start of the platform installer will point n00bs in the right direction.
=> Added an early exit for unsupported OS environments

gcp/README.md
Vault is not currently configured to use a certificate. You need to configure the status command to hit the HTTP endpoint rather than the HTTPS endpoint
Same as here in Azure:
https://github.com/fermyon/installer/commit/b8b99da69cb359c29dd3393c74df215afc8255aa
=> Update vault status command in gcp readme

local/start.sh
- [fix(local): Typo in OSTYPE matching](https://github.com/fermyon/installer/commit/800384cc8082376a21a70b4b24f4b3b6fc2f194a)
Rename cgywin to cygwin.
- [feat(local): Make OS check stricter](https://github.com/fermyon/installer/commit/a1e0149424fb967b7628b8760caaa967fe3196b2)
Match exactly by `linux-gnu` rather than `linux`. Though I believe
it's possible to run platform on `linux-musl` (Alpine Linux) the
local script doesn't currently support it.
Caveats:
- bash isn't installed out of the box
- binary version of Hippo isn't starting up (but hippo compiled from the sources seems to work)
- sudo is only available in the community repo
- consul is installed into /usr/sbin. In this case the whole script has to be run from sudo. Otherwise, consul won't be found in PATH.
- [feat(local): …
=> Improve local setup script

.github/workflows/build.yml, azure/terraform/main.tf, share/terraform/dependencies.yaml
This PR updates Bindle, Spin and Hippo.
Bindle stays on 0.8.0 but the checksum is updated following the recreation of the blob store.
Hippo moves to 0.19 to be consistent with Spin 0.5; the older version was causing https://github.com/fermyon/spin/issues/782.
Spin moves to 0.5.0 to be consistent with client dev environments using this version of the platform.
=> Update Bindle, Spin and Hippo

digitalocean/README.md, digitalocean/terraform/variables.tf, local/job/hippo.nomad
Refs: #105.
Also, fix a few typos in digitalocean docs.
=> chore(local): Bump hippo to v0.19.0

.github/workflows/build.yml, azure/terraform/main.tf, share/terraform/dependencies.yaml
Bump Spin to [v0.6.0](https://github.com/fermyon/spin/releases/tag/v0.6.0) as well as other dependency versions for the cloud installers.
=> chore(*): bump dependencies

aws/.gitignore, aws/README.md, aws/terraform/multiple-nodes/README.md, aws/terraform/single-node/README.md, azure/README.md, digitalocean/README.md, docs/content/index.md, docs/content/quickstart-aws.md, gcp/README.md
Some AWS-related docs updates/re-org following https://github.com/fermyon/installer/pull/100 cc @FrankYang0529 
- Re-introduce top-level AWS readme
- Remove some duplication from the single/multi-node readmes
- minor updates
=> docs(aws): updates per single-node/multi-node scenarios

docs/content/quickstart-local.md
Add instructions to run `spin templates install` before creating a new application from a template.
=> Add templates installation step to Local Quickstart guide

.github/workflows/deploy.yml
Explicitly sets the tailscale version to the [most recent](https://github.com/tailscale/tailscale/releases/tag/v1.78.1) as of writing.
Otherwise, the most recent v2 release of the GH action ([alas, not very recent](https://github.com/tailscale/github-action/releases/tag/v2)) defaults to a very old 1.42.0 version of tailscale.
=> fix(.github): pin tailscale to 1.78.1 for deploy
